version: '3.7'

services:
  receiver:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: receiver
    ports:
      - '3001:3001'
    volumes:
      - ./:/receiver
      - /receiver/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
